security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
            algorithm: auto
            cost: 15

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        # Pour le dev
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Routes publiques : inscription, login, etc.
        public_api:
            pattern: ^/(register|health)$
            security: false

        # Firewall pour login JWT
        login:
            pattern: ^/api/login
            stateless: true
            json_login:
                check_path: /api/login
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            provider: app_user_provider
            custom_authenticator: App\Security\LoginFormAuthenticator

        # Firewall pour routes protégées par JWT
        api:
            pattern: ^/api
            stateless: true
            provider: app_user_provider
            jwt: ~

    access_control:
        # Routes publiques
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/app, roles: PUBLIC_ACCESS }

        # Routes utilisateur authentifié
        - { path: ^/publication, roles: ROLE_USER }
        - { path: ^/comment, roles: ROLE_USER }

        # Routes admin
        - { path: ^/admin, roles: ROLE_ADMIN }

        # Tout ce qui commence par /api nécessite l'authentification
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
